on: [push]

name: AzureDeploy

permissions:
    id-token: write
    contents: read

jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:
      - name: Log in with Azure
        uses: azure/login@v1
        with:
          creds: '${{ secrets.AZURE_SECRETS }}'
          allow-no-subscriptions: true
      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: 'jm-powershell-githubaction'
          slot-name: 'Production'
          #package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          #publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_D54FBBC58258463D922F6EF347AD8B5D }}  